CREATE TABLE `items` (
	`id` varchar(64) NOT NULL,
	`ownerId` int NOT NULL,
	`brand` text,
	`collab` text,
	`season` text,
	`model` text,
	`feature` text,
	`item` text,
	`cost` int NOT NULL DEFAULT 0,
	`price` int NOT NULL DEFAULT 0,
	`size` text,
	`color` text,
	`rank` text,
	`accessories` text,
	`number` text,
	`date` varchar(10),
	`shop` text,
	`category` text,
	`buyer` text,
	`buyerComment` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `items_id` PRIMARY KEY(`id`)
);
